version: '3'
services:
  web:
    image: hemna6969/aprsd-irc-website:latest
    container_name: aprs-irc-website
    volumes:
      - ./app:/app
      - ./logs:/logs
      - ./config:/app/config
    ports:
      - 4001:80
    restart: unless-stopped
    environment:
      - PORT=80
