version: '3'
services:
  web:
    image: hemna6969/aprsd-irc-website:latest
    volumes:
      - ./app:/app
      - ./logs:/logs
      - ./config:/app/config
    ports:
      - 4001:80
    restart: unless-stopped
    environment:
      #- FLASK_APP=main.py
      - FLASK_DEBUG=1
        #- 'RUN=flask run --host=0.0.0.0 --port=80'
      - PORT=80
